chair:
  - id: 'USENIX Security 2027'
    long: '36th USENIX Security Symposium'
    role: 'Open Science and Compliance Chair'
    url: 'https://www.usenix.org/conference/usenixsecurity27/call-for-papers'

  - id: 'uASC 2026'
    role: 'General Chair'
    long: '2nd Microarchitecture Security Conference'
    url: 'https://uasc.cc/'

  - id: 'SysTEX 2024'
    long: '7th Workshop on System Software for Trusted Execution'
    role: 'PC co-chair'
    url: 'https://systex24.github.io'

organizer:
  - id: 'Dagstuhl Seminar #26042'
    long: 'Trustworthy System Architectures for the Age of Custom Silicon'
    url: 'https://www.dagstuhl.de/en/seminars/seminar-calendar/seminar-details/26042'

  - id: 'FOSDEM Confidential Computing Devroom'
    long: "Free and Open source Software Developers' European Meeting"
    url: "https://fosdem.org/"
    eds: [
            [2026, 'https://fosdem.org/2026/schedule/track/confidential-computing/'],
            [2025, 'https://fosdem.org/2025/schedule/track/confidential/'],
            [2024, 'https://fosdem.org/2024/schedule/track/confidential-computing/'],
            [2023, 'https://archive.fosdem.org/2023/schedule/track/confidential_computing/'],
            [2022, 'https://archive.fosdem.org/2022/schedule/track/hardware_aided_trusted_computing/'],
            [2021, 'https://archive.fosdem.org/2021/schedule/track/hardware_aided_trusted_computing/'],
            [2020, 'https://archive.fosdem.org/2020/schedule/track/hardware_aided_trusted_computing/']
         ]

ae:
  - id: 'SysTEX 2025, SysTEX 2024'

steering:
  - id: 'uASC'
    year: '2025-current'
    long: 'Microarchitecture Security Conference'
    url: 'https://uasc.cc/'

grant:
  - id: 'European Research Council - ERC'
    years: [ 2026, 2021 ]

  - id: 'Swedish Research Council'
    years: [ 2025 ]

  - id: 'Dutch Research Council - NWO'
    years: [ 2026 ]

pc:
  - id: 'USENIX Security'
    years: [2026, 2025, 2024]
    awards:
      - { year: 2025, label: 'Distinguished Reviewer Award' }

  - id: 'ACM CCS'
    years: [2023, 2022]
    awards:
      - { year: 2022, label: 'Best Reviewer Award' }
      - { year: 2023, label: 'Top Reviewer Award' }

  - id: 'DIMVA'
    years: [ 2026, 2023, 2022 ]

  - id: 'IEEE SEED'
    years: [ 2024 ]

  - id: 'SysTEX'
    years: [ 2026, 2025, 2023, 2022 ]

  - id: 'uASC'
    years: [ 2025 ]
  
  - id: 'PAVeTrust'
    years: [ 2024, 2023, 2022, 2021 ]

journal:
  - id: 'Computers & Security'
    years: [ 2022, 2021 ]

  - id: 'ACM Computing Surveys'
    years: [ 2020 ]

  - id: 'IEEE Transactions on Dependable and Secure Computing'
    years: [ 2020 ]

  - id: 'IEEE Access'
    years: [ 2019 ]

sub:
  - id: 'IEEE S&P'
    years: [2023, 2021, 2020, 2019, 2017]

  - id: 'ACM CCS'
    years: [2019, 2018]

  - id: 'USENIX Security'
    years: [2017]

  - id: 'ESORICS'
    years: [2017]

  - id: 'POST'
    years: [2017]

  - id: 'SysTEX'
    years: [2017]
